name: Email Action

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: 23f3000789@ds.study.iitm.ac.in
        run: echo "Hello, world!"

      - name: Done
        run: echo "Action completed"
